services:
  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - suthub

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rbtmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - suthub

  app:
    build:
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - "${PORT}:8000"
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - suthub

    volumes:
      - ./:/app

volumes:
  mongo_data:

networks:
  suthub:
    driver: bridge
    name: suthub
