services:
  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - suthub

  age-groups-api:
    build:
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - "${PORT}:8000"
    depends_on:
      - mongo
    networks:
      - suthub

    volumes:
      - ./:/app

volumes:
  mongo_data:

networks:
  suthub:
    driver: bridge
    name: suthub
