from pydantic import BaseModel, Field, ConfigDict


class AgeGroupBase(BaseModel):
    name: str
    min_age: int = Field(..., ge=0, lt=200, description="Minimum age for group")
    max_age: int = Field(..., ge=0, lt=200, description="Maximum age for group")

    model_config = ConfigDict(
        str_strip_whitespace=True
    )


class AgeGroupCreate(AgeGroupBase):
    pass


class AgeGroupRead(AgeGroupBase):
    id: str = Field(..., description="Unique identifier generated by MongoDB")

    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_by_name=True,
        json_schema_extra={
            "example": {
                "id": "6412f6a5e3b1c8f1a2d3e4b5",
                "name": "Young Adults",
                "min_age": 18,
                "max_age": 25
            }
        }
    )
